<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="https://learning.oreilly.com/library/cover/9781491912126/250w/" width=100>

*This notebook contains an excerpt from the [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do) by Jake VanderPlas.*

*The text is released under the [CC-BY-NC-ND license](https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode), and code is released under the [MIT license](https://opensource.org/licenses/MIT). If you find this content useful, please consider supporting the work by [buying the book](http://shop.oreilly.com/product/0636920034919.do)!*

<div>
    <img src="https://numpy.org/images/logo.svg" width="203"/>
</div>

# Outline <a class="anchor" id="Outline"></a>

* [Introduction](#introduction)
* [Understanding Data Types in Python](#understanding_data_types_in_python)
    * [A Python List Is More Than Just a List](#a_python_list_is_more_than_just_a_list)
    * [Creating Arrays from Python Lists](#creating_arrays_from_python_lists)
    * [Creating Arrays from Scratch](#creating_arrays_from_scratch)
    * [NumPy Standard Data Types](#numpy_standard_data_types)
* [The Basics of NumPy Arrays](#the_basics_of_numpy_arrays)
    * [NumPy Array Attributes](#numpy_array_attributes)
    * [Array Indexing: Accessing Single Elements](#array_indexing_accessing_single_elements)
    * [Array Slicing: Accessing Subarrays](#array_slicing_accessing_subarrays)
        * [One-dimensional Subarrays](#one_dimensional_subarrays)
        * [Multi-dimensional Subarrays](#multi_dimensional_subarrays)
            * [Accessing array rows and columns](#accessing_array_rows_and_columns)
        * [Subarrays as no-copy views](#subarrays_as_no_copy_views)
        * [Creating copies of arrays](#creating_copies_of_arrays)
    * [Reshaping of Arrays](#reshaping_of_arrays)
    * [Array Concatenation and Splitting](#array_concatenation_and_splitting)
        * [Concatenation of arrays](#concatenation_of_arrays)
        * [Splitting of arrays](#splitting_of_arrays)
* [Computation on NumPy Arrays: Universal Functions](#computation_on_numpy_arrays_universal_functions)
    * [Introducing UFuncs](#introducing_ufuncs)
    * [Exploring NumPy's UFuncs](#exploring_numpys_ufuncs)
        * [Array arithmetic](#array_arithmetic)
        * [Absolute value](#absolute_value)
        * [Trigonometric functions](#trigonometric_functions)
        * [Exponents and logarithms](#exponents_and_logarithms)
        * [Specialized ufuncs](#specialized_ufuncs)
    * [Advanced Ufunc Features](#advanced_ufunc_features)
        * [Specifying output](#specifying_output)
        * [Outer products](#outer_products)
* [Aggregations: Min, Max, and Everything In Between](aggregations_min_max_and_everything_in_between)
    * [Summing the Values in an Array](#summing_the_values_in_an_array)
    * [Minimum and Maximum](#minimum_and_maximum)
        * [Multi dimensional aggregates](#multi_dimensional_aggregates)
        * [Other aggregation functions](#other_aggregation_functions)
* [Computation on Arrays: Broadcasting](#computation_on_arrays_broadcasting)
    * [Introducing Broadcasting](#introducing_broadcasting)
    * [Rules of Broadcasting](#rules_of_broadcasting)
        * [Broadcasting example 1](#broadcasting_example_1)
        * [Broadcasting example 2](#broadcasting_example_2)
        * [Broadcasting example 3](#broadcasting_example_3)
    * [Broadcasting in Practice](#broadcasting_in_practice)
        * [Centering an array](#centering_an_array)
* [Comparisons, Masks, and Boolean Logic](#comparisons_masks_and_boolean_logic)
    * [Comparison Operators as ufuncs](#comparison_operators_as_ufuncs)
    * [Working with Boolean Arrays](#working_with_boolean_arrays)
        * [Counting entries](#counting_entries)
    * [Boolean Arrays as Masks](#boolean_arrays_as_masks)


# Introduction <a class="anchor" id="introduction"></a> [&#11014;](#Outline)

This notebook, outlines techniques for effectively loading, storing, and manipulating in-memory data in Python.
The topic is very broad: datasets can come from a wide range of sources and a wide range of formats, including be collections of documents, collections of images, collections of sound clips, collections of numerical measurements, or nearly anything else.
Despite this apparent heterogeneity, it will help us to think of all data fundamentally as arrays of numbers.

For example, images–particularly digital images–can be thought of as simply two-dimensional arrays of numbers representing pixel brightness across the area.
Sound clips can be thought of as one-dimensional arrays of intensity versus time.
Text can be converted in various ways into numerical representations, perhaps binary digits representing the frequency of certain words or pairs of words.
No matter what the data are, the first step in making it analyzable will be to transform them into arrays of numbers.

For this reason, efficient storage and manipulation of numerical arrays is absolutely fundamental to the process of doing data science.

This notebook will cover NumPy in detail. NumPy (short for *Numerical Python*) provides an efficient interface to store and operate on dense data buffers.
In some ways, NumPy arrays are like Python's built-in ``list`` type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size.
NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python, so time spent learning to use NumPy effectively will be valuable no matter what aspect of data science interests you.

By convention, you'll find that most programmers in the world will import NumPy using ``np`` as an alias:

In [1]:
import numpy as np

# return the version of the installed numpy package
np.__version__

'1.25.2'

IPython gives you the ability to quickly explore the contents of a package (by using the tab-completion feature), as well as the documentation of various functions (using the ``?`` character).

For example, to display all the contents of the numpy namespace, you can type this:

```ipython
In [3]: np.<TAB>
```

And to display NumPy's built-in documentation, you can use this:

```ipython
In [4]: np?
```
More detailed documentation, along with tutorials and other resources, can be found at http://www.numpy.org.

# Understanding Data Types in Python <a class="anchor" id="understanding_data_types_in_python"></a> [&#11014;](#Outline)

Effective data-driven science and computation requires understanding how data is stored and manipulated.
This section outlines and contrasts how arrays of data are handled in the Python language itself, and how NumPy improves on this.
Understanding this difference is fundamental to understanding much of the material throughout the rest of the course.

Users of Python are often drawn-in by its ease of use, one piece of which is dynamic typing.
While a statically-typed language like C or Java requires each variable to be explicitly declared, a dynamically-typed language like Python skips this specification. For example, in C you might specify a particular operation as follows:

```C
/* C code */
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}
```

While in Python the equivalent operation could be written this way:

```python
# Python code
result = 0
for i in range(100):
    result += i
```

Notice the main difference: in C, the data types of each variable are explicitly declared, while in Python the types are dynamically inferred. This means, for example, that we can assign any kind of data to any variable:

```python
# Python code
x = 4
x = "four"
```

Here we've switched the contents of ``x`` from an integer to a string. The same thing in C would lead (depending on compiler settings) to a compilation error or other unintented consequences:

```C
/* C code */
int x = 4;
x = "four";  // FAILS
```

This sort of flexibility is one piece that makes Python and other dynamically-typed languages convenient and easy to use.
Understanding *how* this works is an important piece of learning to analyze data efficiently and effectively with Python.

## A Python List Is More Than Just a List <a class="anchor" id="a_python_list_is_more_than_just_a_list"></a> [&#11014;](#Outline)

Let's consider now what happens when we use a Python data structure that holds many Python objects.
The standard mutable multi-element container in Python is the list.
We can create a list of integers as follows:

In [2]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
type(L[0])

int

Or, similarly, a list of strings:

In [4]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [5]:
type(L2[0])

str

Because of Python's dynamic typing, we can even create heterogeneous lists:

In [6]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

But this flexibility comes at a cost: to allow these flexible types, each item in the list must contain its own type info, reference count, and other information–that is, each item is a complete Python object.
In the special case that all variables are of the same type, much of this information is redundant: it can be much more efficient to store data in a fixed-type array.
The difference between a dynamic-type list and a fixed-type (NumPy-style) array is illustrated in the following figure:

![Array Memory Layout](figures/array_vs_list.png)

At the implementation level, the array essentially contains a single pointer to one contiguous block of data.
The Python list, on the other hand, contains a pointer to a block of pointers, each of which in turn points to a full Python object like the Python integer we saw earlier.
Again, the advantage of the list is flexibility: because each list element is a full structure containing both data and type information, the list can be filled with data of any desired type.
Fixed-type NumPy-style arrays lack this flexibility, but are much more efficient for storing and manipulating data.

## Creating Arrays from Python Lists <a class="anchor" id="creating_arrays_from_python_lists"></a> [&#11014;](#Outline)

First, we can use ``np.array`` to create arrays from Python lists:

In [7]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type.
If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point):

In [8]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

If we want to explicitly set the data type of the resulting array, we can use the ``dtype`` keyword:

In [9]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Finally, unlike Python lists, NumPy arrays can explicitly be multi-dimensional; here's one way of initializing a multidimensional array using a list of lists:

In [10]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The inner lists are treated as rows of the resulting two-dimensional array.

## Creating Arrays from Scratch <a class="anchor" id="creating_arrays_from_scratch"></a> [&#11014;](#Outline)

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy.
Here are several examples:

In [11]:
# Create a length-10 integer array filled with zeros
print("np.zeros(10, dtype=int):", np.zeros(10, dtype=int), "\n")

# Create a 3x5 floating-point array filled with ones
print("np.ones((3, 5), dtype=float):\n", np.ones((3, 5), dtype=float), "\n")

# Create a 3x5 array filled with 3.14
print("np.full((3, 5), 3.14):\n", np.full((3, 5), 3.14), "\n")

# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
print("np.arange(0, 20, 2):", np.arange(0, 20, 2), "\n")

# Create an array of five values evenly spaced between 0 and 1
print("np.linspace(0, 1, 5):", np.linspace(0, 1, 5), "\n")

# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
print("np.random.random((3, 3)):\n", np.random.random((3, 3)), "\n")

# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
print("np.random.normal(0, 1, (3, 3)):\n", np.random.normal(0, 1, (3, 3)), "\n")

# Create a 3x3 array of random integers in the interval [0, 10)
print("np.random.randint(0, 10, (3, 3)):\n", np.random.randint(0, 10, (3, 3)), "\n")

# Create a 3x3 identity matrix
print("np.eye(3):\n", np.eye(3), "\n")

# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
print("np.empty(3):", np.empty(3))

np.zeros(10, dtype=int): [0 0 0 0 0 0 0 0 0 0] 

np.ones((3, 5), dtype=float):
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

np.full((3, 5), 3.14):
 [[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]] 

np.arange(0, 20, 2): [ 0  2  4  6  8 10 12 14 16 18] 

np.linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ] 

np.random.random((3, 3)):
 [[0.93340348 0.89200711 0.92082024]
 [0.72059757 0.9611463  0.94333636]
 [0.88910037 0.41753543 0.12023553]] 

np.random.normal(0, 1, (3, 3)):
 [[-0.54918933 -1.49043887  0.61690565]
 [-1.06835846 -1.42833535  1.88131685]
 [-1.54069712  0.9050563  -1.34230756]] 

np.random.randint(0, 10, (3, 3)):
 [[6 4 4]
 [8 1 8]
 [4 6 2]] 

np.eye(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

np.empty(3): [1. 1. 1.]


## NumPy Standard Data Types <a class="anchor" id="numpy_standard_data_types"></a> [&#11014;](#Outline)

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations.
Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

The standard NumPy data types are listed in the following table.
Note that when constructing an array, they can be specified using a string:

```python
np.zeros(10, dtype='int16')
```

Or using the associated NumPy object:

```python
np.zeros(10, dtype=np.int16)
```

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

More advanced type specification is possible, such as specifying big or little endian numbers; for more information, refer to the [NumPy documentation](http://numpy.org/).

# The Basics of NumPy Arrays <a class="anchor" id="the_basics_of_numpy_arrays"></a> [&#11014;](#Outline)

Data manipulation in Python is nearly synonymous with NumPy array manipulation.
This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.

We'll cover a few categories of basic array manipulations here:

- *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays
- *Indexing of arrays*: Getting and setting the value of individual array elements
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array
- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many

## NumPy Array Attributes <a class="anchor" id="numpy_array_attributes"></a> [&#11014;](#Outline)

First let's discuss some useful array attributes.
We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.
We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [12]:
np.random.seed(10)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [13]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Another useful attribute is the ``dtype``, the data type of the array:

In [14]:
print("x3 dtype:", x3.dtype)

x3 dtype: int32


## Array Indexing: Accessing Single Elements <a class="anchor" id="array_indexing_accessing_single_elements"></a> [&#11014;](#Outline)

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [15]:
print("x1:", x1)

print("x1[0]:", x1[0])
print("x1[4]:", x1[4])

x1: [9 4 0 1 9 0]
x1[0]: 9
x1[4]: 9


To index from the end of the array, you can use negative indices:

In [16]:
print("x1[-1]:", x1[-1])
print("x1[-2]:", x1[-2])

x1[-1]: 0
x1[-2]: 9


In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [17]:
print("x2:\n", x2, "\n")

print("x2[0, 0]:", x2[0, 0])
print("x2[2, 0]:", x2[2, 0])
print("x2[2, -1]:", x2[2, -1])

x2:
 [[1 8 9 0]
 [8 6 4 3]
 [0 4 6 8]] 

x2[0, 0]: 1
x2[2, 0]: 0
x2[2, -1]: 8


Values can also be modified using any of the above index notation:

In [18]:
x2[0, 0] = 12
x2

array([[12,  8,  9,  0],
       [ 8,  6,  4,  3],
       [ 0,  4,  6,  8]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [19]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 4, 0, 1, 9, 0])

## Array Slicing: Accessing Subarrays <a class="anchor" id="array_slicing_accessing_subarrays"></a> [&#11014;](#Outline)

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional Subarrays <a class="anchor" id="one_dimensional_subarrays"></a> [&#11014;](#Outline)

In [20]:
x = np.arange(10)
print("x:", x)

print("x[:5]:", x[:5])  # first five elements
print("x[5:]:", x[5:])  # elements after index 5
print("x[4:7]:", x[4:7])  # middle sub-array
print("x[::2]:", x[::2])  # every other element
print("x[1::2]:", x[1::2])  # every other element, starting at index 1

x: [0 1 2 3 4 5 6 7 8 9]
x[:5]: [0 1 2 3 4]
x[5:]: [5 6 7 8 9]
x[4:7]: [4 5 6]
x[::2]: [0 2 4 6 8]
x[1::2]: [1 3 5 7 9]


A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [21]:
print("x[::-1]:", x[::-1])  # all elements, reversed
print("x[5::-2]:", x[5::-2])  # reversed every other from index 5 with step 2

x[::-1]: [9 8 7 6 5 4 3 2 1 0]
x[5::-2]: [5 3 1]


### Multi-dimensional Subarrays <a class="anchor" id="multi_dimensional_subarrays"></a> [&#11014;](#Outline)

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [22]:
print("x2:\n", x2, "\n")

print("x2[:2, :3]:\n", x2[:2, :3], "\n")  # two rows, three columns
print("x2[:3, ::2]:\n", x2[:3, ::2])  # all rows, every other column

x2:
 [[12  8  9  0]
 [ 8  6  4  3]
 [ 0  4  6  8]] 

x2[:2, :3]:
 [[12  8  9]
 [ 8  6  4]] 

x2[:3, ::2]:
 [[12  9]
 [ 8  4]
 [ 0  6]]


Finally, subarray dimensions can even be reversed together:

In [23]:
x2[::-1, ::-1]

array([[ 8,  6,  4,  0],
       [ 3,  4,  6,  8],
       [ 0,  9,  8, 12]])

#### Accessing array rows and columns <a class="anchor" id="accessing_array_rows_and_columns"></a> [&#11014;](#Outline)

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [24]:
print("x2[:, 0]:", x2[:, 0])  # first column of x2
print("x2[0, :]:", x2[0, :])  # first row of x2

x2[:, 0]: [12  8  0]
x2[0, :]: [12  8  9  0]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [25]:
x2[0]  # equivalent to x2[0, :]

array([12,  8,  9,  0])

### Subarrays as no-copy views <a class="anchor" id="subarrays_as_no_copy_views"></a> [&#11014;](#Outline)

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [26]:
x2

array([[12,  8,  9,  0],
       [ 8,  6,  4,  3],
       [ 0,  4,  6,  8]])

Let's extract a $2 \times 2$ subarray from this:

In [27]:
x2_sub = x2[:2, :2]
x2_sub

array([[12,  8],
       [ 8,  6]])

Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [28]:
x2_sub[0, 0] = 99

print("x2_sub:\n", x2_sub, "\n")
print("x2:\n", x2)

x2_sub:
 [[99  8]
 [ 8  6]] 

x2:
 [[99  8  9  0]
 [ 8  6  4  3]
 [ 0  4  6  8]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays <a class="anchor" id="creating_copies_of_arrays"></a> [&#11014;](#Outline)

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [29]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[99,  8],
       [ 8,  6]])

If we now modify this subarray, the original array is not touched:

In [30]:
x2_sub_copy[0, 0] = 42

print("x2_sub_copy:\n", x2_sub_copy, "\n")
print("x2:\n", x2)

x2_sub_copy:
 [[42  8]
 [ 8  6]] 

x2:
 [[99  8  9  0]
 [ 8  6  4  3]
 [ 0  4  6  8]]


## Reshaping of Arrays <a class="anchor" id="reshaping_of_arrays"></a> [&#11014;](#Outline)

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [31]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Note that for this to work, the size of the initial array must match the size of the reshaped array.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [32]:
x = np.array([1, 2, 3])
print("x:", x)

print("x.reshape((1, 3)):", x.reshape((1, 3)))  # row vector via reshape
print("x[np.newaxis, :]:", x[np.newaxis, :])  # row vector via newaxis
print("x.reshape((3, 1)):\n", x.reshape((3, 1)), "\n")  # column vector via reshape
print("x[:, np.newaxis]:\n", x[:, np.newaxis])  # column vector via newaxis

x: [1 2 3]
x.reshape((1, 3)): [[1 2 3]]
x[np.newaxis, :]: [[1 2 3]]
x.reshape((3, 1)):
 [[1]
 [2]
 [3]] 

x[:, np.newaxis]:
 [[1]
 [2]
 [3]]


## Array Concatenation and Splitting <a class="anchor" id="array_concatenation_and_splitting"></a> [&#11014;](#Outline)

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays <a class="anchor" id="concatenation_of_arrays"></a> [&#11014;](#Outline)

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack`` .
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [33]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

print("x:", x)
print("y:", y)
print("np.concatenate([x, y]):", np.concatenate([x, y]))

x: [1 2 3]
y: [3 2 1]
np.concatenate([x, y]): [1 2 3 3 2 1]


You can also concatenate more than two arrays at once:

In [34]:
z = [99, 99, 99]

np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

It can also be used for two-dimensional arrays:

In [35]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("grid: \n", grid, "\n")
# concatenate along the first axis
print("np.concatenate([grid, grid]):\n", np.concatenate([grid, grid]), "\n")
# concatenate along the second axis (zero-indexed)
print("np.concatenate([grid, grid], axis=1):\n", np.concatenate([grid, grid], axis=1))

grid: 
 [[1 2 3]
 [4 5 6]] 

np.concatenate([grid, grid]):
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]] 

np.concatenate([grid, grid], axis=1):
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [36]:
x = np.array([1, 2, 3])
y = np.array([[99],
              [99]])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

print("x:", x)
print("y:\n", y, "\n")
print("grid:\n", grid, "\n")
print("np.vstack([x, grid]):\n", np.vstack([x, grid]), "\n")  # vertically stack the arrays
print("np.hstack([grid, y]):\n", np.hstack([grid, y]))  # horizontally stack the arrays

x: [1 2 3]
y:
 [[99]
 [99]] 

grid:
 [[9 8 7]
 [6 5 4]] 

np.vstack([x, grid]):
 [[1 2 3]
 [9 8 7]
 [6 5 4]] 

np.hstack([grid, y]):
 [[ 9  8  7 99]
 [ 6  5  4 99]]


### Splitting of arrays <a class="anchor" id="splitting_of_arrays"></a> [&#11014;](#Outline)

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

In [37]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])

print("x:", x)
print("x1:", x1)
print("x2:", x2)
print("x3:", x3)

x: [1, 2, 3, 99, 99, 3, 2, 1]
x1: [1 2 3]
x2: [99 99]
x3: [3 2 1]


Notice that *N* split-points, leads to *N + 1* subarrays.
The related functions ``np.hsplit`` and ``np.vsplit`` are similar:

In [38]:
grid = np.arange(16).reshape((4, 4))
upper, lower = np.vsplit(grid, [2])
left, right = np.hsplit(grid, [2])

print("grid:\n", grid, "\n")
print("upper:\n", upper, "\n")
print("lower:\n", lower, "\n")
print("left:\n", left, "\n")
print("right:\n", right)

grid:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

upper:
 [[0 1 2 3]
 [4 5 6 7]] 

lower:
 [[ 8  9 10 11]
 [12 13 14 15]] 

left:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

right:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Computation on NumPy Arrays: Universal Functions <a class="anchor" id="computation_on_numpy_arrays_universal_functions"></a> [&#11014;](#Outline)

Up until now, we have been discussing some of the basic nuts and bolts of NumPy; in the next few sections, we will dive into the reasons that NumPy is so important in the Python data science world.
Namely, it provides an easy and flexible interface to optimized computation with arrays of data.

Computation on NumPy arrays can be very fast, or it can be very slow.
The key to making it fast is to use *vectorized* operations, generally implemented through NumPy's *universal functions* (ufuncs).
This section motivates the need for NumPy's ufuncs, which can be used to make repeated calculations on array elements much more efficient.
It then introduces many of the most common and useful arithmetic ufuncs available in the NumPy package.

## Introducing UFuncs <a class="anchor" id="introducing_ufuncs"></a> [&#11014;](#Outline)

For many types of operations, NumPy provides a convenient interface into just this kind of statically typed, compiled routine. This is known as a *vectorized* operation.
This can be accomplished by simply performing an operation on the array, which will then be applied to each element.
This vectorized approach is designed to push the loop into the compiled layer that underlies NumPy, leading to much faster execution.

In [39]:
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)

print("values:", values)
print("compute_reciprocals(values):", compute_reciprocals(values))
print("1.0 / values:", 1.0 / values)

values: [6 1 4 4 8]
compute_reciprocals(values): [0.16666667 1.         0.25       0.25       0.125     ]
1.0 / values: [0.16666667 1.         0.25       0.25       0.125     ]


Looking at the execution time for our big array, we see that it completes orders of magnitude faster than the Python loop:

In [40]:
big_array = np.random.randint(1, 100, size=1000000)

%timeit compute_reciprocals(big_array)
%timeit (1.0 / big_array)

1.58 s ± 62.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.06 ms ± 496 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Vectorized operations in NumPy are implemented via *ufuncs*, whose main purpose is to quickly execute repeated operations on values in NumPy arrays.
Ufuncs are extremely flexible – before we saw an operation between a scalar and an array, but we can also operate between two arrays:

In [41]:
print("np.arange(5):", np.arange(5))
print("np.arange(1, 6):", np.arange(1, 6))
print("np.arange(5) / np.arange(1, 6):", np.arange(5) / np.arange(1, 6))

np.arange(5): [0 1 2 3 4]
np.arange(1, 6): [1 2 3 4 5]
np.arange(5) / np.arange(1, 6): [0.         0.5        0.66666667 0.75       0.8       ]


And ufunc operations are not limited to one-dimensional arrays–they can also act on multi-dimensional arrays as well:

In [42]:
x = np.arange(9).reshape((3, 3))

print("x:\n", x, "\n")
print("2 ** x:\n", 2 ** x)

x:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

2 ** x:
 [[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]


Computations using vectorization through ufuncs are nearly always more efficient than their counterpart implemented using Python loops, especially as the arrays grow in size.
Any time you see such a loop in a Python script, you should consider whether it can be replaced with a vectorized expression.

## Exploring NumPy's UFuncs <a class="anchor" id="exploring_numpys_ufuncs"></a> [&#11014;](#Outline)

Ufuncs exist in two flavors: *unary ufuncs*, which operate on a single input, and *binary ufuncs*, which operate on two inputs.
We'll see examples of both these types of functions here.

### Array arithmetic <a class="anchor" id="array_arithmetic"></a> [&#11014;](#Outline)

NumPy's ufuncs feel very natural to use because they make use of Python's native arithmetic operators.
The standard addition, subtraction, multiplication, and division can all be used:

In [43]:
x = np.arange(4)
print("x =", x)

print("-x =", -x)  # negation
print("x + 5 =", x + 5)  # addition
print("x - 5 =", x - 5)  # subtraction
print("x * 2 =", x * 2)  # multiplication
print("x / 2 =", x / 2)  # division
print("x // 2 =", x // 2)  # floor division
print("x ** 2 =", x**2)  # exponantiation
print("x % 2 =", x % 2)  # modulus

x = [0 1 2 3]
-x = [ 0 -1 -2 -3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]


In addition, these can be strung together however you wish, and the standard order of operations is respected:

In [44]:
-((0.5 * x + 1) ** 2)

array([-1.  , -2.25, -4.  , -6.25])

Each of these arithmetic operations are simply convenient wrappers around specific functions built into NumPy; for example, the ``+`` operator is a wrapper for the ``add`` function:

In [45]:
np.add(x, 2)

array([2, 3, 4, 5])

The following table lists the arithmetic operators implemented in NumPy:

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|

### Absolute value <a class="anchor" id="absolute_value"></a> [&#11014;](#Outline)

Just as NumPy understands Python's built-in arithmetic operators, it also understands Python's built-in absolute value function:

In [46]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

The corresponding NumPy ufunc is ``np.absolute``, which is also available under the alias ``np.abs``:

In [47]:
print("np.absolute(x):", np.absolute(x))
print("np.abs(x):", np.abs(x))

np.absolute(x): [2 1 0 1 2]
np.abs(x): [2 1 0 1 2]


This ufunc can also handle complex data, in which the absolute value returns the magnitude:

In [48]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

### Trigonometric functions <a class="anchor" id="trigonometric_functions"></a> [&#11014;](#Outline)

NumPy provides a large number of useful ufuncs, and some of the most useful for the data scientist are the trigonometric functions.
We'll start by defining an array of angles:

In [49]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

Now we can compute some trigonometric functions on these values:

In [50]:
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta) =", np.tan(theta))

sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


The values are computed to within machine precision, which is why values that should be zero do not always hit exactly zero.

Inverse trigonometric functions are also available:

In [51]:
x = np.array([-1, 0, 1])
print("x =", x)

print("arcsin(x) =", np.arcsin(x))
print("arccos(x) =", np.arccos(x))
print("arctan(x) =", np.arctan(x))

x = [-1  0  1]
arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


### Exponents and logarithms <a class="anchor" id="exponents_and_logarithms"></a> [&#11014;](#Outline)

Another common type of operation available in a NumPy ufunc are the exponentials:

In [52]:
x = np.array([1, 2, 3])
print("x =", x)

print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1 2 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


The inverse of the exponentials, the logarithms, are also available.
The basic ``np.log`` gives the natural logarithm; if you prefer to compute the base-2 logarithm or the base-10 logarithm, these are available as well:

In [53]:
x = np.array([1, 2, 4, 10])
print("x =", x)

print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))
print("log5(x) =", np.log(x) / np.log(5))  # Logarithm of x with arbitrary base

x = [ 1  2  4 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]
log5(x) = [0.         0.43067656 0.86135312 1.43067656]


There are also some specialized versions that are useful for maintaining precision with very small input:

In [54]:
x = np.array([0, 0.001, 0.01, 0.1])
print("x:", x)

print("exp(x) - 1 =", np.expm1(x))
print("exp(x) - 1 =", np.exp(x) - 1)
%timeit (np.expm1(x))
%timeit (np.exp(x) - 1)

print("log(1 + x) =", np.log1p(x))
print("log(1 + x) =", np.log(1 + x))
%timeit (np.log1p(x))
%timeit (np.log(1 + x))

x: [0.    0.001 0.01  0.1  ]
exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
584 ns ± 53.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
2.07 µs ± 146 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]
532 ns ± 34.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
1.72 µs ± 66 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


When ``x`` is very small, these functions give more precise values than if the raw ``np.log`` or ``np.exp`` were to be used.

### Specialized ufuncs <a class="anchor" id="specialized_ufuncs"></a> [&#11014;](#Outline)

NumPy has many more ufuncs available, including hyperbolic trig functions, bitwise arithmetic, comparison operators, conversions from radians to degrees, rounding and remainders, and much more.
A look through the NumPy documentation reveals a lot of interesting functionality.

Another excellent source for more specialized and obscure ufuncs is the submodule ``scipy.special``.
If you want to compute some obscure mathematical function on your data, chances are it is implemented in ``scipy.special``.
There are far too many functions to list them all, but the following snippet shows a couple that might come up in a statistics context:

In [55]:
from scipy import special

$$\Gamma(n) = (n - 1)!$$
$$\Beta(m, n) = \frac{(m - 1)! (n - 1)!}{(m + n - 1)!}$$

In [56]:
# Gamma functions (generalized factorials) and related functions
x = np.array([1, 5, 10])
print("x:", x)

print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

x: [ 1  5 10]
gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


$$\mathrm{erf}(x) = \frac{2}{\sqrt{\pi}} \int_{0}^{x} e^{-t^{2}} dt$$
$$\mathrm{erfc}(x) = 1 - \mathrm{erf}(x)$$
$$\mathrm{erf}(\mathrm{erf}^{-1} x) = x$$

In [57]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("x:", x)

print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))
print("erf(erfinv(x)) =", special.erf(special.erfinv(x)))

x: [0.  0.3 0.7 1. ]
erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]
erf(erfinv(x)) = [0.  0.3 0.7 1. ]


## Advanced Ufunc Features <a class="anchor" id="advanced_ufunc_features"></a> [&#11014;](#Outline)

Many NumPy users make use of ufuncs without ever learning their full set of features.
We'll outline a few specialized features of ufuncs here.

### Specifying output <a class="anchor" id="specifying_output"></a> [&#11014;](#Outline)

For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored.
Rather than creating a temporary array, this can be used to write computation results directly to the memory location where you'd like them to be.
For all ufuncs, this can be done using the ``out`` argument of the function:

In [58]:
x = np.arange(5)
y = np.empty(5)
print("x:", x)
print("y:", y)

np.multiply(x, 10, out=y)
print("x:", y)
print("y:", y)

x: [0 1 2 3 4]
y: [0.         0.5        0.66666667 0.75       0.8       ]
x: [ 0. 10. 20. 30. 40.]
y: [ 0. 10. 20. 30. 40.]


This can even be used with array views. For example, we can write the results of a computation to every other element of a specified array:

In [59]:
y = np.zeros(10, dtype=int)
print("y:", y)

np.power(2, x, out=y[::2])
print("new y:", y)

y: [0 0 0 0 0 0 0 0 0 0]
new y: [ 1  0  2  0  4  0  8  0 16  0]


If we had instead written ``y[::2] = 2 ** x``, this would have resulted in the creation of a temporary array to hold the results of ``2 ** x``, followed by a second operation copying those values into the ``y`` array.
This doesn't make much of a difference for such a small computation, but for very large arrays the memory savings from careful use of the ``out`` argument can be significant.

### Outer products <a class="anchor" id="outer_products"></a> [&#11014;](#Outline)

Finally, any ufunc can compute the output of all pairs of two different inputs using the ``outer`` method.
This allows you, in one line, to do things like create a multiplication table:

In [60]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

More information on universal functions (including the full list of available functions) can be found on the [NumPy](http://www.numpy.org) and [SciPy](http://www.scipy.org) documentation websites.

# Aggregations: Min, Max, and Everything In Between <a class="anchor" id="aggregations_min_max_and_everything_in_between"></a> [&#11014;](#Outline)

Often when faced with a large amount of data, a first step is to compute summary statistics for the data in question.
Perhaps the most common summary statistics are the mean and standard deviation, which allow you to summarize the "typical" values in a dataset, but other aggregates are useful as well (the sum, product, median, minimum and maximum, quantiles, etc.).

NumPy has fast built-in aggregation functions for working on arrays; we'll discuss and demonstrate some of them here.

## Summing the Values in an Array <a class="anchor" id="summing_the_values_in_an_array"></a> [&#11014;](#Outline)

As a quick example, consider computing the sum of all values in an array.
Python itself can do this using the built-in ``sum`` function:

In [61]:
L = np.random.random(100)
sum(L)

50.461758453195614

The syntax is quite similar to that of NumPy's ``sum`` function, and the result is the same in the simplest case:

In [62]:
np.sum(L)

50.46175845319564

However, because it executes the operation in compiled code, NumPy's version of the operation is computed much more quickly:

In [63]:
big_array = np.random.rand(1000000)

%timeit sum(big_array)
%timeit np.sum(big_array)

71 ms ± 4.61 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.38 ms ± 81.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## Minimum and Maximum <a class="anchor" id="minimum_and_maximum"></a> [&#11014;](#Outline)

Similarly, Python has built-in ``min`` and ``max`` functions, used to find the minimum value and maximum value of any given array:

In [64]:
print("min(big_array):", min(big_array))
print("max(big_array):", max(big_array))

min(big_array): 7.071203171893359e-07
max(big_array): 0.9999997207656334


NumPy's corresponding functions have similar syntax, and again operate much more quickly:

In [65]:
print("np.min(big_array):", np.min(big_array))
print("np.max(big_array):", np.max(big_array))

np.min(big_array): 7.071203171893359e-07
np.max(big_array): 0.9999997207656334


In [66]:
%timeit min(big_array)
%timeit np.min(big_array)

47.4 ms ± 566 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
420 µs ± 6.79 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


For ``min``, ``max``, ``sum``, and several other NumPy aggregates, a shorter syntax is to use methods of the array object itself:

In [67]:
print("big_array.min():", big_array.min())
print("big_array.max():", big_array.max())
print("big_array.sum():", big_array.sum())

big_array.min(): 7.071203171893359e-07
big_array.max(): 0.9999997207656334
big_array.sum(): 500216.8034810001


Whenever possible, make sure that you are using the NumPy version of these aggregates when operating on NumPy arrays!

### Multi dimensional aggregates <a class="anchor" id="multi_dimensional_aggregates"></a> [&#11014;](#Outline)

One common type of aggregation operation is an aggregate along a row or column.
Say you have some data stored in a two-dimensional array:

In [68]:
M = np.random.random((3, 4))
M

array([[0.79832448, 0.44923861, 0.95274259, 0.03193135],
       [0.18441813, 0.71417358, 0.76371195, 0.11957117],
       [0.37578601, 0.11936151, 0.37497044, 0.22944653]])

By default, each NumPy aggregation function will return the aggregate over the entire array:

In [69]:
M.sum()

5.1136763453287335

Aggregation functions take an additional argument specifying the *axis* along which the aggregate is computed. For example, we can find the minimum value within each column by specifying ``axis=0``:

In [70]:
M.min(axis=0)

array([0.18441813, 0.11936151, 0.37497044, 0.03193135])

The function returns four values, corresponding to the four columns of numbers.

Similarly, we can find the maximum value within each row:

In [71]:
M.max(axis=1)

array([0.95274259, 0.76371195, 0.37578601])

The way the axis is specified here can be confusing to users coming from other languages.
The ``axis`` keyword specifies the *dimension of the array that will be collapsed*, rather than the dimension that will be returned.
So specifying ``axis=0`` means that the first axis will be collapsed: for two-dimensional arrays, this means that values within each column will be aggregated.

### Other aggregation functions <a class="anchor" id="other_aggregation_functions"></a> [&#11014;](#Outline)

NumPy provides many other aggregation functions, but we won't discuss them in detail here.
Additionally, most aggregates have a ``NaN``-safe counterpart that computes the result while ignoring missing values.

The following table provides a list of useful aggregation functions available in NumPy:

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |

# Computation on Arrays: Broadcasting <a class="anchor" id="computation_on_arrays_broadcasting"></a> [&#11014;](#Outline)

We saw in the previous section how NumPy's universal functions can be used to *vectorize* operations and thereby remove slow Python loops.
Another means of vectorizing operations is to use NumPy's *broadcasting* functionality.
Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.

## Introducing Broadcasting <a class="anchor" id="introducing_broadcasting"></a> [&#11014;](#Outline)

Recall that for arrays of the same size, binary operations are performed on an element-by-element basis:

In [72]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])

print("a:", a)
print("b:", b)
print("a + b:", a + b)

a: [0 1 2]
b: [5 5 5]
a + b: [5 6 7]


Broadcasting allows these types of binary operations to be performed on arrays of different sizes–for example, we can just as easily add a scalar (think of it as a zero-dimensional array) to an array:

In [73]:
print("a:", a)
print("a + 5:", a + 5)

a: [0 1 2]
a + 5: [5 6 7]


We can think of this as an operation that stretches or duplicates the value ``5`` into the array ``[5, 5, 5]``, and adds the results.

We can similarly extend this to arrays of higher dimension. Observe the result when we add a one-dimensional array to a two-dimensional array:

In [74]:
M = np.ones((3, 3))

print("M:\n", M, "\n")
print("a:\n", a, "\n")
print("M + a:\n", M + a)

M:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

a:
 [0 1 2] 

M + a:
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


Here the one-dimensional array ``a`` is stretched, or broadcast across the second dimension in order to match the shape of ``M``.

While these examples are relatively easy to understand, more complicated cases can involve broadcasting of both arrays. Consider the following example:

In [75]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print("a:\n", a, "\n")
print("b:\n", b, "\n")
print("a + b:\n", a + b)

a:
 [0 1 2] 

b:
 [[0]
 [1]
 [2]] 

a + b:
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


Just as before we stretched or broadcasted one value to match the shape of the other, here we've stretched *both* ``a`` and ``b`` to match a common shape, and the result is a two-dimensional array!
The geometry of these examples is visualized in the following figure.

![Broadcasting Visual](figures/array_broadcasting.png)

The light boxes represent the broadcasted values: again, this extra memory is not actually allocated in the course of the operation, but it can be useful conceptually to imagine that it is.

## Rules of Broadcasting <a class="anchor" id="rules_of_broadcasting"></a> [&#11014;](#Outline)

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

- Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is *padded* with ones on its leading (left) side.
- Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
- Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

To make these rules clear, let's consider a few examples in detail.

### Broadcasting example 1 <a class="anchor" id="broadcasting_example_1"></a> [&#11014;](#Outline)

Let's look at adding a two-dimensional array to a one-dimensional array:

In [76]:
M = np.ones((2, 3))
a = np.arange(3)

print("M:\n", M, "\n")
print("a:\n", a, "\n")

M:
 [[1. 1. 1.]
 [1. 1. 1.]] 

a:
 [0 1 2] 



Let's consider an operation on these two arrays. The shape of the arrays are

- ``M.shape = (2, 3)``
- ``a.shape = (3,)``

We see by rule 1 that the array ``a`` has fewer dimensions, so we pad it on the left with ones:

- ``M.shape -> (2, 3)``
- ``a.shape -> (1, 3)``

By rule 2, we now see that the first dimension disagrees, so we stretch this dimension to match:

- ``M.shape -> (2, 3)``
- ``a.shape -> (2, 3)``

The shapes match, and we see that the final shape will be ``(2, 3)``:

In [77]:
print("M + a:\n", M + a)

M + a:
 [[1. 2. 3.]
 [1. 2. 3.]]


### Broadcasting example 2 <a class="anchor" id="broadcasting_example_2"></a> [&#11014;](#Outline)

Let's take a look at an example where both arrays need to be broadcast:

In [78]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

print("a:\n", a, "\n")
print("b:\n", b)

a:
 [[0]
 [1]
 [2]] 

b:
 [0 1 2]


Again, we'll start by writing out the shape of the arrays:

- ``a.shape = (3, 1)``
- ``b.shape = (3,)``

Rule 1 says we must pad the shape of ``b`` with ones:

- ``a.shape -> (3, 1)``
- ``b.shape -> (1, 3)``

And rule 2 tells us that we upgrade each of these ones to match the corresponding size of the other array:

- ``a.shape -> (3, 3)``
- ``b.shape -> (3, 3)``

Because the result matches, these shapes are compatible. We can see this here:

In [79]:
print("a + b:\n", a + b)

a + b:
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


### Broadcasting example 3 <a class="anchor" id="broadcasting_example_3"></a> [&#11014;](#Outline)

Now let's take a look at an example in which the two arrays are not compatible:

In [80]:
M = np.ones((3, 2))
a = np.arange(3)

print("M:\n", M, "\n")
print("a:\n", a)

M:
 [[1. 1.]
 [1. 1.]
 [1. 1.]] 

a:
 [0 1 2]


This is just a slightly different situation than in the first example: the matrix ``M`` is transposed.
How does this affect the calculation? The shape of the arrays are

- ``M.shape = (3, 2)``
- ``a.shape = (3,)``

Again, rule 1 tells us that we must pad the shape of ``a`` with ones:

- ``M.shape -> (3, 2)``
- ``a.shape -> (1, 3)``

By rule 2, the first dimension of ``a`` is stretched to match that of ``M``:

- ``M.shape -> (3, 2)``
- ``a.shape -> (3, 3)``

Now we hit rule 3–the final shapes do not match, so these two arrays are incompatible, as we can observe by attempting this operation:

In [81]:
print("M + a:\n", M + a)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

## Broadcasting in Practice <a class="anchor" id="broadcasting_in_practice"></a> [&#11014;](#Outline)

Broadcasting operations form the core of many examples we'll see throughout this notebook.
We'll now take a look at a couple simple examples of where they can be useful.

### Centering an array <a class="anchor" id="centering_an_array"></a> [&#11014;](#Outline)

In the previous section, we saw that ufuncs allow a NumPy user to remove the need to explicitly write slow Python loops. Broadcasting extends this ability.
One commonly seen example is when centering an array of data.
Imagine you have an array of 10 observations, each of which consists of 3 values.
Using the standard convention, we'll store this in a $10 \times 3$ array:

In [82]:
X = np.random.random((10, 3))
X

array([[0.07452786, 0.41843762, 0.99939192],
       [0.66974416, 0.54717434, 0.82711104],
       [0.23097044, 0.16283152, 0.27950484],
       [0.58540569, 0.90657413, 0.18671025],
       [0.07262851, 0.0068539 , 0.07533272],
       [0.77114754, 0.94502816, 0.79396332],
       [0.81250458, 0.68306202, 0.09142216],
       [0.72943166, 0.49977781, 0.88075176],
       [0.77188336, 0.33609389, 0.35670153],
       [0.26486376, 0.51351043, 0.18439926]])

We can compute the mean of each feature using the ``mean`` aggregate across the first dimension:

In [83]:
X_mean = X.mean(axis=0)
X_mean

array([0.49831076, 0.50193438, 0.46752888])

And now we can center the ``X`` array by subtracting the mean (this is a broadcasting operation):

In [84]:
X_centered = X - X_mean
X_centered

array([[-0.42378289, -0.08349676,  0.53186304],
       [ 0.1714334 ,  0.04523996,  0.35958216],
       [-0.26734032, -0.33910286, -0.18802404],
       [ 0.08709493,  0.40463975, -0.28081862],
       [-0.42568224, -0.49508048, -0.39219616],
       [ 0.27283678,  0.44309377,  0.32643444],
       [ 0.31419383,  0.18112764, -0.37610672],
       [ 0.23112091, -0.00215657,  0.41322288],
       [ 0.2735726 , -0.16584049, -0.11082735],
       [-0.23344699,  0.01157605, -0.28312962]])

To double-check that we've done this correctly, we can check that the centered array has near zero mean:

In [85]:
X_centered_mean = X_centered.mean(axis=0)
X_centered_mean

array([-4.44089210e-17,  3.33066907e-17, -9.43689571e-17])

To within machine precision, the mean is now zero.

# Comparisons, Masks, and Boolean Logic <a class="anchor" id="comparisons_masks_and_boolean_logic"></a> [&#11014;](#Outline)

This section covers the use of Boolean masks to examine and manipulate values within NumPy arrays.
Masking comes up when you want to extract, modify, count, or otherwise manipulate values in an array based on some criterion: for example, you might wish to count all values greater than a certain value, or perhaps remove all outliers that are above some threshold.
In NumPy, Boolean masking is often the most efficient way to accomplish these types of tasks.

## Comparison Operators as ufuncs <a class="anchor" id="comparison_operators_as_ufuncs"></a> [&#11014;](#Outline)

NumPy implements comparison operators such as ``<`` (less than) and ``>`` (greater than) as element-wise ufuncs.
The result of these comparison operators is always an array with a Boolean data type.
All six of the standard comparison operations are available:

In [86]:
x = np.array([1, 2, 3, 4, 5])
print("x:", x)

print("x < 3:", x < 3)  # less than
print("x > 3:", x < 3)  # greater than
print("x <= 3:", x <= 3)  # less than or equal
print("x >= 3:", x >= 3)  # greater than or equal
print("x != 3:", x != 3)  # not equal
print("x == 3:", x == 3)  # equal

x: [1 2 3 4 5]
x < 3: [ True  True False False False]
x > 3: [ True  True False False False]
x <= 3: [ True  True  True False False]
x >= 3: [False False  True  True  True]
x != 3: [ True  True False  True  True]
x == 3: [False False  True False False]


It is also possible to do an element-wise comparison of two arrays, and to include compound expressions:

In [87]:
print("x:", x)
print("(2 * x) == (x ** 2):", (2 * x) == (x ** 2))

x: [1 2 3 4 5]
(2 * x) == (x ** 2): [False  True False False False]


As in the case of arithmetic operators, the comparison operators are implemented as ufuncs in NumPy; for example, when you write ``x < 3``, internally NumPy uses ``np.less(x, 3)``.
    A summary of the comparison operators and their equivalent ufunc is shown here:

| Operator | Equivalent ufunc     |
| :------- | :------------------- |
| ``==``   | ``np.equal``         |
| ``<``    | ``np.less``          |
| ``>``    | ``np.greater``       |
| ``!=``   | ``np.not_equal``     |
| ``<=``   | ``np.less_equal``    |
| ``>=``   | ``np.greater_equal`` |

Just as in the case of arithmetic ufuncs, these will work on arrays of any size and shape.
Here is a two-dimensional example:

In [88]:
rng = np.random.RandomState(0)

x = rng.randint(10, size=(3, 4))
print("x:\n", x, "\n")

print("x < 6:\n", x < 6)

x:
 [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

x < 6:
 [[ True  True  True  True]
 [False False  True  True]
 [ True  True False False]]


In each case, the result is a Boolean array, and NumPy provides a number of straightforward patterns for working with these Boolean results.

## Working with Boolean Arrays <a class="anchor" id="working_with_boolean_arrays"></a> [&#11014;](#Outline)

Given a Boolean array, there are a host of useful operations you can do.
We'll work with ``x``, the two-dimensional array we created earlier.

### Counting entries <a class="anchor" id="counting_entries"></a> [&#11014;](#Outline)

To count the number of ``True`` entries in a Boolean array, ``np.count_nonzero`` is useful:

In [89]:
print("x:\n", x, "\n")

# how many values less than 6?
print("np.count_nonzero(x < 6):", np.count_nonzero(x < 6))

x:
 [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

np.count_nonzero(x < 6): 8


We see that there are eight array entries that are less than 6.
Another way to get at this information is to use ``np.sum``; in this case, ``False`` is interpreted as ``0``, and ``True`` is interpreted as ``1``:

In [90]:
print("x:\n", x, "\n")

# how many values less than 6?
print("np.sum(x < 6):", np.sum(x < 6))

x:
 [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

np.sum(x < 6): 8


The benefit of ``sum()`` is that like with other NumPy aggregation functions, this summation can be done along rows or columns as well:

In [91]:
print("x:\n", x)

# how many values less than 6 in each row?
print("np.sum(x < 6, axis=1):", np.sum(x < 6, axis=1))

x:
 [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
np.sum(x < 6, axis=1): [4 2 2]


This counts the number of values less than 6 in each row of the matrix.

If we're interested in quickly checking whether any or all the values are true, we can use (you guessed it) ``np.any`` or ``np.all``:

In [92]:
print("x:\n", x)

# are there any values greater than 8?
print("np.any(x > 8):", np.any(x > 8))
# are there any values less than zero?
print("np.any(x < 0):", np.any(x < 0))
# are all values less than 10?
print("np.all(x < 10):", np.all(x < 10))
# are all values equal to 6?
print("np.all(x == 6):", np.all(x == 6))

x:
 [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
np.any(x > 8): True
np.any(x < 0): False
np.all(x < 10): True
np.all(x == 6): False


``np.all`` and ``np.any`` can be used along particular axes as well. For example:

In [93]:
print("x:\n", x)

# are all values in each row less than 8?
np.all(x < 8, axis=1)

x:
 [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


array([ True, False,  True])

Here all the elements in the first and third rows are less than 8, while this is not the case for the second row.

## Boolean Arrays as Masks <a class="anchor" id="boolean_arrays_as_masks"></a> [&#11014;](#Outline)

In the preceding section we looked at aggregates computed directly on Boolean arrays.
A more powerful pattern is to use Boolean arrays as masks, to select particular subsets of the data themselves.
Returning to our ``x`` array from before, suppose we want an array of all values in the array that are less than, say, 5.
We can obtain a Boolean array for this condition easily, as we've already seen:

In [94]:
print("x:\n", x, "\n")

print("x < 5:\n", x < 5)

x:
 [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

x < 5:
 [[False  True  True  True]
 [False False  True False]
 [ True  True False False]]


Now to *select* these values from the array, we can simply index on this Boolean array; this is known as a *masking* operation:

In [95]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])

What is returned is a one-dimensional array filled with all the values that meet this condition; in other words, all the values in positions at which the mask array is ``True``.