# Special Topics I Problem Set 2 (NumPy)

## Q1

Take two integer numbers from the user and create a $3 \times 3 \times 3$ array with random integer values between these numbers.

In [1]:
# import numpy package
import numpy as np

# getting the 1st number from the user
n1 = int(input("Please enter the 1st number: "))
# getting the 2nd number from the user
n2 = int(input("Please enter the 2nd number: "))

# make the desired array
desired_array = np.random.randint(
    low=np.min([n1, n2]), high=np.max([n1, n2]) + 1, size=(3, 3, 3)
)

# print number n1
print("n1 =", n1)
# print number n2
print("n2 =", n2)
# print answer
print("output: \n", desired_array)

n1 = 3
n2 = 10
output: 
 [[[ 6  3  7]
  [ 4 10  4]
  [ 6  3  7]]

 [[ 9  9  5]
  [ 7  4  7]
  [ 9  5  5]]

 [[ 6  9  6]
  [ 5 10  6]
  [10  7  7]]]


## Q2

Generate a 2D array whose elements have a Gaussian distribution.

In [2]:
# import numpy package
import numpy as np


# sigma(standard deviation) and mu(mean) are the parameters of gaussian
def gaussian_filter(kernel_size, sigma=1, mu=0):
    # initializing value of x, y as grid of kernel size in the range of kernel size
    x, y = np.meshgrid(np.linspace(-1, 1, kernel_size), np.linspace(-1, 1, kernel_size))
    dst = np.sqrt(x**2 + y**2)

    # lower normal part of gaussian
    normal = 1 / (2 * np.pi * sigma**2)

    # calculating gaussian filter
    gauss = np.exp(-((dst - mu) ** 2 / (2.0 * sigma**2))) * normal

    return gauss


# specify kernel size
kernel_size = 5
# applying the written function and built the desired array
gaussian = gaussian_filter(kernel_size)

# print answer
print("gaussian filter of {} x {} :".format(kernel_size, kernel_size), "\n", gaussian)

gaussian filter of 5 x 5 : 
 [[0.05854983 0.0851895  0.09653235 0.0851895  0.05854983]
 [0.0851895  0.12394999 0.14045374 0.12394999 0.0851895 ]
 [0.09653235 0.14045374 0.15915494 0.14045374 0.09653235]
 [0.0851895  0.12394999 0.14045374 0.12394999 0.0851895 ]
 [0.05854983 0.0851895  0.09653235 0.0851895  0.05854983]]


## Q3

Define an arbitrary array and make it immutable. (read-only)

In [3]:
# import numpy package
import numpy as np

# make a zeros array
Z = np.zeros(10)
# make the array immutable
Z.flags.writeable = False

# checking if it works properly or not
Z[0] = 1

ValueError: assignment destination is read-only

## Q4

Write a function that takes an array and a number $n$ as input and returns the $n^{th}$ largest number of the array.

In [4]:
# import numpy package
import numpy as np


# define our function
def nth_largest_number(array, n):
    return np.sort(array.flatten())[-n]


nth_largest_number(np.array([[66, 15, 35], [90, 34, 7], [85, 79, 43]]), 4)

66

## Q5

Write a program that takes a number $n$ from the user. Then generate a random number between $1$ and $n$ and put it in variable $m$. Finally, generate an $n \times n$ array whose elements are between $0$ and $n$ and sort the rows of this array based on the values of the $m^{th}$ column and print the result.

In [5]:
# getting the number n from the user
n = int(input("Please enter the number n: "))
# generating the number m
m = np.random.randint(low=1, high=n + 1)

# generating the array
random_array = np.random.randint(low=0, high=n + 1, size=(n, n))
# sorting the array based on the values of the mth column
sorted_random_array = random_array[random_array[:, m - 1].argsort()]

# print number n
print("n =", n)
# print number m
print("m =", m, "\n")
# print the array
print("random_array:\n", random_array, "\n")
# print the answer (sorted array)
print("sorted_random_array:\n", sorted_random_array)

n = 4
m = 4 

random_array:
 [[2 1 4 0]
 [1 4 3 4]
 [3 4 4 2]
 [0 0 4 2]] 

sorted_random_array:
 [[2 1 4 0]
 [3 4 4 2]
 [0 0 4 2]
 [1 4 3 4]]


<div class="alert alert-block alert-info">

**Attention:** To do this series of exercises, you are only allowed to use numpy library functions.
</div>

Good luck 😉